"""machine and kit tables

Revision ID: df218c3aa780
Revises: 
Create Date: 2020-09-26 14:32:22.264206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df218c3aa780'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=8), nullable=True),
    sa.Column('serialnum', sa.String(length=64), nullable=True),
    sa.Column('customer', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_project'), 'machine', ['project'], unique=True)
    op.create_index(op.f('ix_machine_serialnum'), 'machine', ['serialnum'], unique=True)
    op.create_table('kit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('length', sa.String(length=8), nullable=True),
    sa.Column('width', sa.String(length=8), nullable=True),
    sa.Column('depth', sa.String(length=8), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kit')
    op.drop_index(op.f('ix_machine_serialnum'), table_name='machine')
    op.drop_index(op.f('ix_machine_project'), table_name='machine')
    op.drop_table('machine')
    # ### end Alembic commands ###
